apiVersion: apps/v1
kind: Deployment
metadata:
  name: ecocycle-backend
spec:
  selector:
    matchLabels:
      app: ecocycle-backend
  replicas: 1
  template:
    metadata:
      labels:
        app: ecocycle-backend
    spec:
      containers:
        - name: ecocycle-backend
          image: ignaciodev11/ecocycle-services:tag # Reemplaza con la ruta de tu imagen
          ports:
            - containerPort: 8000
          env:
            - name: DATABASE_HOST
              value: "ecocycle-db-service"
            - name: DATABASE_PORT
              value: "5432"
            - name: DATABASE_NAME
              value: "ecocycle"
            - name: DATABASE_USER
              value: "ecocycleadmin"
            - name: DATABASE_URL
              value: postgres://ecocycleadmin:password@ecocycle-db-service:5432/ecocycle
            - name: SECRET_KEY
              value: secretkey
            - name: ENV
              value: development
            - name: PORT
              value: "8000"
            - name: BONITA_URL
              value: http://192.168.0.92:8080/bonita
            - name: BONITA_USERNAME
              value: walter.bates
            - name: BONITA_PASS
              value: bpm
            - name: SUPERUSER_USERNAME
              value: admin
            - name: SUPERUSER_EMAIL
              value: admin@example.com
            - name: SUPERUSER_PASSWORD
              value: admin
            - name: DATABASE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-secret
                  key: POSTGRES_PASSWORD
