# Generated by Django 5.1.1 on 2024-09-20 22:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recolectores', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DepositoComunal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('hide', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'depositos_comunales',
            },
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('hide', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'materiales',
            },
        ),
        migrations.RenameField(
            model_name='orden',
            old_name='cantidad',
            new_name='cantidad_inicial',
        ),
        migrations.AddField(
            model_name='orden',
            name='case_bonita_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='orden',
            name='estado',
            field=models.CharField(choices=[('Pendiente', 'Pendiente'), ('Procesado', 'Procesado'), ('Cancelado', 'Cancelado')], default='Pendiente', max_length=10),
        ),
        migrations.AddField(
            model_name='orden',
            name='deposito',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recolectores.depositocomunal'),
        ),
        migrations.AlterField(
            model_name='orden',
            name='material',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recolectores.material'),
        ),
    ]
