# Generated by Django 5.1.1 on 2024-10-08 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recolectores', '0002_depositocomunal_material_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orden',
            name='cantidad_final',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
