# Generated by Django 5.1.1 on 2024-10-09 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recolectores', '0005_reserva'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserva',
            name='case_bonita_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
