# Generated by Django 5.1.1 on 2024-10-09 20:04

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recolectores', '0007_alter_reserva_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockDeposito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(1)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deposito', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recolectores.depositocomunal')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recolectores.material')),
            ],
            options={
                'db_table': 'stock_depositos',
            },
        ),
    ]
