# Generated by Django 5.1.1 on 2024-10-10 15:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recolectores', '0008_stockdeposito'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrdenDistribucion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('Pendiente', 'Pendiente'), ('Procesado', 'Procesado'), ('Cancelado', 'Cancelado')], default='Pendiente', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deposito', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recolectores.depositocomunal')),
                ('reserva', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recolectores.reserva')),
            ],
            options={
                'db_table': 'ordenes_distribucion',
            },
        ),
    ]
