# Generated by Django 5.1.1 on 2024-10-25 01:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recolectores', '0010_material_precio_notificaciondiscrepancia_pago'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserva',
            name='deposito_encargado',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='recolectores.depositocomunal'),
        ),
        migrations.AddField(
            model_name='reserva',
            name='fecha_entrega',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reserva',
            name='fecha_prevista',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='estado',
            field=models.CharField(choices=[('Pendiente', 'Pendiente'), ('Procesado', 'Procesado'), ('Cancelado', 'Cancelado'), ('Completado', 'Completado')], default='Pendiente', max_length=10),
        ),
        migrations.DeleteModel(
            name='OrdenDistribucion',
        ),
    ]
