# Generated by Django 5.1.1 on 2024-11-04 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recolectores', '0011_reserva_deposito_encargado_reserva_fecha_entrega_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stockdeposito',
            name='deposito',
        ),
        migrations.RemoveField(
            model_name='orden',
            name='deposito',
        ),
        migrations.RemoveField(
            model_name='reserva',
            name='deposito_encargado',
        ),
        migrations.RemoveField(
            model_name='usermaterial',
            name='material',
        ),
        migrations.RemoveField(
            model_name='stockdeposito',
            name='material',
        ),
        migrations.RemoveField(
            model_name='reserva',
            name='material',
        ),
        migrations.RemoveField(
            model_name='orden',
            name='material',
        ),
        migrations.RemoveField(
            model_name='notificaciondiscrepancia',
            name='orden',
        ),
        migrations.RemoveField(
            model_name='orden',
            name='empleado',
        ),
        migrations.RemoveField(
            model_name='orden',
            name='recolector',
        ),
        migrations.RemoveField(
            model_name='pago',
            name='orden',
        ),
        migrations.RenameField(
            model_name='reserva',
            old_name='user',
            new_name='solicitante',
        ),
        migrations.RenameField(
            model_name='usermaterial',
            old_name='user',
            new_name='proveedor',
        ),
        migrations.AddField(
            model_name='reserva',
            name='deposito_encargado_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reserva',
            name='material_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='usermaterial',
            name='material_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='DepositoComunal',
        ),
        migrations.DeleteModel(
            name='StockDeposito',
        ),
        migrations.DeleteModel(
            name='Material',
        ),
        migrations.DeleteModel(
            name='NotificacionDiscrepancia',
        ),
        migrations.DeleteModel(
            name='Orden',
        ),
        migrations.DeleteModel(
            name='Pago',
        ),
    ]
