# Generated by Django 5.1.1 on 2024-11-04 00:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recolectores', '0012_alter_reserva_fecha_entrega_and_more'),
        ('recolectores', '0012_remove_stockdeposito_deposito_remove_orden_deposito_and_more'),
    ]

    operations = [
    ]
